- name: Install required dependencies
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - curl
    state: present
    update_cache: yes

- name: Add Docker's official RHEL 9 repo
  get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Enable Docker RHEL 9 repo
  ini_file:
    path: /etc/yum.repos.d/docker-ce.repo
    section: "docker-ce-stable"
    option: "enabled"
    value: "1"

- name: Install Docker engine, CLI, and Compose plugin
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: true
    state: started