- name: Rocky Linux 9 Update  
  hosts: all
  become: true

  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Update all packages
     ansible.builtin.yum:
       name: '*'
       state: latest

   - name: Reboot if needed
     ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible after package update"
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: whoami

   - name: Print message
     ansible.builtin.debug:
       msg: All packages have been updated to the latest version on Rocky Linux 9 hosts!!